version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]

volumes:
  postgres_data:
  static:
  staticfiles:
