version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]

  celery:
    build: .
    restart: always
    depends_on:
      - redis
      - web
    env_file:
      - .env
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]

  celery-beat:
    build: .
    restart: always
    depends_on:
      - web
      - redis
    env_file:
      - .env
    command: ["celery", "-A", "config", "beat", "--loglevel=info"]

volumes:
  postgres_data: