# Generated by Django 4.2.16 on 2025-01-23 07:22

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=appointment.models.default_appointment_name, max_length=150, verbose_name='Наименование')),
                ('appointment_number_int', models.IntegerField(null=True, verbose_name='Номер записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('canceled', 'Отменен'), ('completed', 'Завершен')], default='Новый', max_length=150, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Прием врача',
                'verbose_name_plural': 'Прием врачей',
            },
        ),
    ]
