# Generated by Django 4.2.16 on 2025-01-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('speciality', models.CharField(blank=True, max_length=150, null=True, verbose_name='Специальность')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='service/photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
    ]
